// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2025-2026 Rocket Chip Project
// AUTO-GENERATED by scripts/generate_profile.py
// GENERATED_FROM: profiles/hab.cfg (sha256: a79ef4cd3d6b02b3)
//
// Do not edit this file directly.
// Edit profiles/hab.cfg and re-run the generator.

#ifndef ROCKETCHIP_TEST_HAB_PROFILE_DATA_H
#define ROCKETCHIP_TEST_HAB_PROFILE_DATA_H
#include "mission_profile.h"
#include "rocketchip/radio_config.h"

namespace rc {

inline constexpr MissionProfile kHabProfile = {
    .id = ProfileId::kHab,
    .name = "HAB",

    .armed_timeout_ms = 600000,
    .abort_timeout_ms = 300000,
    .coast_timeout_ms = 60000,
    .launch_accel_threshold = 5.0f,
    .launch_sustain_ms = 100,
    .burnout_accel_threshold = 3.0f,
    .burnout_sustain_ms = 200,
    .apogee_velocity_threshold = 1.0f,
    .apogee_sustain_ms = 100,
    .baro_peak_sustain_ms = 500,
    .main_deploy_altitude_m = 500.0f,
    .main_deploy_sustain_ms = 100,
    .landing_velocity_threshold = 0.5f,
    .landing_sustain_ms = 3000,
    .baro_landing_rate_threshold_mps = 0.3f,
    .baro_landing_sustain_ms = 5000,
    .descent_max_duration_ms = 3600000,
    .deploy_lockout_mps = 20.0f,
    .apogee_lockout_ms = 5000,
    .burnout_backup_ms = 30000,
    .main_backup_ms = 300000,
    .apogee_require_both = false,
    .abort_fires_drogue_from_boost = false,
    .abort_fires_drogue_from_coast = false,
    .require_gps_lock = true,
    .require_mag_cal = false,
    .require_radio = true,
    .has_pyro = false,
    .drogue_timer_s = 0.0f,
    .main_timer_s = 0.0f,
    .default_lat_deg = 33.0f,
    .default_lon_deg = -97.0f,
    .has_default_location = true,

    .phase_qr = {.phases = {
        // IDLE (0)
        {.q_scale = {1.0f, 1.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // ARMED (1)
        {.q_scale = {1.0f, 1.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // BOOST (2)
        {.q_scale = {2.0f, 5.0f, 2.0f, 2.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // COAST (3)
        {.q_scale = {2.0f, 5.0f, 2.0f, 2.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // DROGUE_DESC (4)
        {.q_scale = {2.0f, 5.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // MAIN_DESC (5)
        {.q_scale = {2.0f, 5.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // LANDED (6)
        {.q_scale = {1.0f, 1.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // ABORT (7)
        {.q_scale = {2.0f, 5.0f, 2.0f, 2.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
    }, .ramp_steps = 20},
};

// Compile-time validation
static_assert(kHabProfile.launch_accel_threshold > 0.0f,
              "LAUNCH_ACCEL must be positive");
static_assert(kHabProfile.main_deploy_altitude_m > 0.0f,
              "MAIN_ALT_M must be positive");
static_assert(kHabProfile.armed_timeout_ms > 0,
              "ARMED_TIMEOUT_MS must be positive");
static_assert(kHabProfile.landing_sustain_ms >= 100,
              "LAND_HOLD_MS must be at least 100ms");
static_assert(kHabProfile.phase_qr.ramp_steps >= 1,
              "QR_RAMP_STEPS must be >= 1");

inline constexpr RadioConfig kHabRadioConfig = {
    .mode             = RadioRole::kTx,
    .protocol         = EncoderType::kCcsds,
    .nav_rate_hz      = 2,
    .power_dbm        = 20,
    .spreading_factor = 7,
    .bandwidth_khz    = 125,
    .coding_rate      = 5,
};

} // namespace rc

#endif  // ROCKETCHIP_TEST_HAB_PROFILE_DATA_H
