// AUTO-GENERATED by scripts/generate_profile.py
// GENERATED_FROM: C:/Users/pow-w/Documents/Rocket-Chip/profiles/hab.cfg (sha256: 1f6a26af801cea01)
//
// Do not edit this file directly.
// Edit C:/Users/pow-w/Documents/Rocket-Chip/profiles/hab.cfg and re-run the generator.

#pragma once
#include "mission_profile.h"

namespace rc {

inline constexpr MissionProfile kHabProfile = {
    .id = ProfileId::kHab,
    .name = "HAB",

    .armed_timeout_ms = 600000,
    .abort_timeout_ms = 300000,
    .coast_timeout_ms = 60000,
    .launch_accel_threshold = 5.0f,
    .launch_sustain_ms = 100,
    .burnout_accel_threshold = 3.0f,
    .burnout_sustain_ms = 200,
    .apogee_velocity_threshold = 1.0f,
    .apogee_sustain_ms = 100,
    .baro_peak_sustain_ms = 500,
    .main_deploy_altitude_m = 500.0f,
    .main_deploy_sustain_ms = 100,
    .landing_velocity_threshold = 0.5f,
    .landing_sustain_ms = 3000,
    .deploy_lockout_mps = 20.0f,
    .apogee_lockout_ms = 5000,
    .burnout_backup_ms = 30000,
    .main_backup_ms = 300000,
    .apogee_require_both = false,
    .emergency_deploy_anytime = true,
    .abort_fires_drogue_from_boost = false,
    .abort_fires_drogue_from_coast = false,
    .require_gps_lock = true,
    .require_mag_cal = false,
    .require_radio = true,
    .has_pyro = false,
};

// Compile-time validation
static_assert(kHabProfile.launch_accel_threshold > 0.0f,
              "LAUNCH_ACCEL must be positive");
static_assert(kHabProfile.main_deploy_altitude_m > 0.0f,
              "MAIN_ALT_M must be positive");
static_assert(kHabProfile.armed_timeout_ms > 0,
              "ARMED_TIMEOUT_MS must be positive");
static_assert(kHabProfile.landing_sustain_ms >= 100,
              "LAND_HOLD_MS must be at least 100ms");

} // namespace rc
