// AUTO-GENERATED by scripts/generate_profile.py
// GENERATED_FROM: profiles/rocket.cfg (sha256: de30717f4d9239ff)
//
// Do not edit this file directly.
// Edit profiles/rocket.cfg and re-run the generator.

#pragma once
#include "mission_profile.h"

namespace rc {

inline constexpr MissionProfile kDefaultRocketProfile = {
    .id = ProfileId::kRocket,
    .name = "Rocket",

    .armed_timeout_ms = 300000,
    .abort_timeout_ms = 300000,
    .coast_timeout_ms = 15000,
    .launch_accel_threshold = 20.0f,
    .launch_sustain_ms = 50,
    .burnout_accel_threshold = 5.0f,
    .burnout_sustain_ms = 100,
    .apogee_velocity_threshold = 0.5f,
    .apogee_sustain_ms = 30,
    .baro_peak_sustain_ms = 200,
    .main_deploy_altitude_m = 150.0f,
    .main_deploy_sustain_ms = 50,
    .landing_velocity_threshold = 0.5f,
    .landing_sustain_ms = 2000,
    .deploy_lockout_mps = 80.0f,
    .apogee_lockout_ms = 3000,
    .burnout_backup_ms = 10000,
    .main_backup_ms = 120000,
    .apogee_require_both = true,
    .emergency_deploy_anytime = false,
    .abort_fires_drogue_from_boost = true,
    .abort_fires_drogue_from_coast = true,
    .require_gps_lock = false,
    .require_mag_cal = false,
    .require_radio = false,
    .has_pyro = true,
};

// Compile-time validation
static_assert(kDefaultRocketProfile.launch_accel_threshold > 0.0f,
              "LAUNCH_ACCEL must be positive");
static_assert(kDefaultRocketProfile.main_deploy_altitude_m > 0.0f,
              "MAIN_ALT_M must be positive");
static_assert(kDefaultRocketProfile.armed_timeout_ms > 0,
              "ARMED_TIMEOUT_MS must be positive");
static_assert(kDefaultRocketProfile.landing_sustain_ms >= 100,
              "LAND_HOLD_MS must be at least 100ms");

} // namespace rc
