// AUTO-GENERATED by scripts/generate_profile.py
// GENERATED_FROM: profiles/rocket.cfg (sha256: a5d0988fecd070c4)
//
// Do not edit this file directly.
// Edit profiles/rocket.cfg and re-run the generator.

#pragma once
#include "mission_profile.h"
#include "rocketchip/radio_config.h"

namespace rc {

inline constexpr MissionProfile kDefaultRocketProfile = {
    .id = ProfileId::kRocket,
    .name = "Rocket",

    .armed_timeout_ms = 300000,
    .abort_timeout_ms = 300000,
    .coast_timeout_ms = 15000,
    .launch_accel_threshold = 20.0f,
    .launch_sustain_ms = 50,
    .burnout_accel_threshold = 5.0f,
    .burnout_sustain_ms = 100,
    .apogee_velocity_threshold = 0.5f,
    .apogee_sustain_ms = 30,
    .baro_peak_sustain_ms = 200,
    .main_deploy_altitude_m = 150.0f,
    .main_deploy_sustain_ms = 50,
    .landing_velocity_threshold = 0.5f,
    .landing_sustain_ms = 2000,
    .deploy_lockout_mps = 80.0f,
    .apogee_lockout_ms = 3000,
    .burnout_backup_ms = 10000,
    .main_backup_ms = 120000,
    .apogee_require_both = true,
    .emergency_deploy_anytime = false,
    .abort_fires_drogue_from_boost = false,
    .abort_fires_drogue_from_coast = false,
    .require_gps_lock = false,
    .require_mag_cal = false,
    .require_radio = false,
    .has_pyro = true,

    .phase_qr = {.phases = {
        // IDLE (0)
        {.q_scale = {1.0f, 1.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // ARMED (1)
        {.q_scale = {1.0f, 1.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // BOOST (2)
        {.q_scale = {10.0f, 50.0f, 5.0f, 5.0f},
         .r = {0.004f, 0.016f, 12.25f, 0.25f}},
        // COAST (3)
        {.q_scale = {5.0f, 10.0f, 2.0f, 2.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // DROGUE_DESC (4)
        {.q_scale = {2.0f, 5.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // MAIN_DESC (5)
        {.q_scale = {2.0f, 5.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // LANDED (6)
        {.q_scale = {1.0f, 1.0f, 1.0f, 1.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
        // ABORT (7)
        {.q_scale = {5.0f, 10.0f, 2.0f, 2.0f},
         .r = {0.001f, 0.008f, 12.25f, 0.25f}},
    }, .ramp_steps = 20},
};

// Compile-time validation
static_assert(kDefaultRocketProfile.launch_accel_threshold > 0.0f,
              "LAUNCH_ACCEL must be positive");
static_assert(kDefaultRocketProfile.main_deploy_altitude_m > 0.0f,
              "MAIN_ALT_M must be positive");
static_assert(kDefaultRocketProfile.armed_timeout_ms > 0,
              "ARMED_TIMEOUT_MS must be positive");
static_assert(kDefaultRocketProfile.landing_sustain_ms >= 100,
              "LAND_HOLD_MS must be at least 100ms");
static_assert(kDefaultRocketProfile.phase_qr.ramp_steps >= 1,
              "QR_RAMP_STEPS must be >= 1");

inline constexpr RadioConfig kDefaultRocketRadioConfig = {
    .mode             = RadioRole::kTx,
    .protocol         = EncoderType::kCcsds,
    .nav_rate_hz      = 5,
    .power_dbm        = 20,
    .spreading_factor = 7,
    .bandwidth_khz    = 125,
    .coding_rate      = 5,
};

} // namespace rc
