// AUTO-GENERATED by scripts/generate_fpft.py -- DO NOT EDIT
#ifndef ESKF_CODEGEN_H
#define ESKF_CODEGEN_H

// Codegen FPFT function declaration
void codegen_fpft(float P[15][15], const float R[3][3],
                  float ax, float ay, float az,
                  float wx, float wy, float wz,
                  float dt_val);

// R3: Sync constants — baked into codegen, must match eskf.h
namespace codegen {
inline constexpr float kSigmaGyro = 0.0002618f;
inline constexpr float kSigmaAccel = 0.002256f;
inline constexpr float kSigmaGyroBiasWalk = 1e-05f;
inline constexpr float kSigmaAccelBiasWalk = 0.0001f;
}  // namespace codegen

#endif  // ESKF_CODEGEN_H
