// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (c) 2025-2026 Rocket Chip Project
#ifndef ROCKETCHIP_FUSION_WMM_DECLINATION_H
#define ROCKETCHIP_FUSION_WMM_DECLINATION_H

// WMM magnetic declination lookup table.
// Bilinear interpolation on a 10° lat/lon grid (19×37 = 703 points).
//
// Data source: ArduPilot AP_Declination/tables.cpp (IGRF13 epoch).
// Table generated by ArduPilot generate/generate.py from IGRF
// coefficients. Float values used directly (no conversion).
//
// Accuracy: ~0.5° typical, up to ~1° in polar regions.
// Valid through ~2028-2029 (IGRF13 secular variation extrapolation).
// Refresh when WMM2030 is published (NOAA, every 5 years).
//
// Future: generate directly from NOAA WMM.COF coefficients to remove
// ArduPilot dependency (see AGENT_WHITEBOARD.md deferred notes).
//
// Reference: ArduPilot AP_Declination, PX4 geo_mag_declination.

namespace rc {

// Get magnetic declination at a GPS position.
// latDeg: geodetic latitude in degrees (-90 to +90)
// lonDeg: geodetic longitude in degrees (-180 to +180)
// Returns: declination in radians (East-positive, same convention as
//   ESKF update_mag_heading declination_rad parameter).
float wmm_get_declination(float latDeg, float lonDeg);

} // namespace rc

#endif // ROCKETCHIP_FUSION_WMM_DECLINATION_H
