// AUTO-GENERATED by scripts/generate_wmm_table.py
// Source: WMM2025 (NOAA/NCEI, public domain)
// Valid: 2025-2030
//
// Do not edit this file directly.
#ifndef ROCKETCHIP_FUSION_WMM_TABLES_H
#define ROCKETCHIP_FUSION_WMM_TABLES_H

#include <stdint.h>
#include "math/vec3.h"

namespace rc {

// Grid parameters
static constexpr int32_t kLatRows = 19;
static constexpr int32_t kLonCols = 37;
static constexpr float kLatMinF = -90.0f;
static constexpr float kLatMaxF = 90.0f;
static constexpr float kLonMinF = -180.0f;
static constexpr float kGridResF = 10.0f;
static constexpr float kDegToRadF = 3.14159265f / 180.0f;

// Full geomagnetic field at a location
struct WmmField {
    float declination_rad;   // East-positive
    float inclination_rad;   // Down-positive
    float intensity_ut;      // Total field magnitude (microtesla)
};

// Get all three geomagnetic components (bilinear interpolated from tables)
WmmField wmm_get_field(float lat_deg, float lon_deg);

// Get declination only (radians, East-positive) — legacy compatibility
float wmm_get_declination(float lat_deg, float lon_deg);

// Compute earth magnetic field NED vector (microtesla) from WMM tables
Vec3 wmm_get_earth_field_ned(float lat_deg, float lon_deg);

} // namespace rc

#endif // ROCKETCHIP_FUSION_WMM_TABLES_H
