<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Big Daddy</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>13</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>292.19189334151844</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>83.0</KnownMass>
                    <Density>1049.2093265</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Nose cone</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>43.15139053358625</CalcMass>
                    <CalcCG>182.57235529435619</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>228.6</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>0.762</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>76.2</BaseDia>
                    <ShoulderLen>76.2</ShoulderLen>
                    <ShoulderOD>73.66</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>85.14554414528222</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>Body tube</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>85.14554414528222</CalcMass>
                    <CalcCG>127.0</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>254.0</Len>
                    <FinishCode>1</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>76.2</OD>
                    <ID>73.66</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>73.66</MotorDia>
                    <EngineOverhang>12.7</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>2.8889023066437494</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Motor mount</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>146.05</Xb>
                            <CalcMass>2.8889023066437494</CalcMass>
                            <CalcCG>50.8</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>101.6</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>24.79</OD>
                            <ID>24.13</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>24.13</MotorDia>
                            <EngineOverhang>4.775</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts>
                                <Ring>
                                    <KnownMass>1.280430238015284</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Engine block</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>29.845</Xb>
                                    <CalcMass>1.280430238015284</CalcMass>
                                    <CalcCG>3.175</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>6.35</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>4</SerialNo>
                                    <OD>24.13</OD>
                                    <ID>18.796</ID>
                                    <UsageCode>2</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                                <MassObject>
                                    <KnownMass>1.389</KnownMass>
                                    <Density>0.0</Density>
                                    <Material></Material>
                                    <Name>Engine hook</Name>
                                    <KnownCG>73.025</KnownCG>
                                    <UseKnownCG>1</UseKnownCG>
                                    <Xb>73.025</Xb>
                                    <CalcMass>0.0</CalcMass>
                                    <CalcCG>0.0</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>0.0</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>5</SerialNo>
                                    <TypeCode>0</TypeCode>
                                </MassObject>
                                <Ring>
                                    <KnownMass>0.14157023378273095</KnownMass>
                                    <Density>1121.29241</Density>
                                    <Material>Paper</Material>
                                    <Name>Sleeve</Name>
                                    <KnownCG>0.0</KnownCG>
                                    <UseKnownCG>0</UseKnownCG>
                                    <Xb>63.5</Xb>
                                    <CalcMass>0.14157023378273095</CalcMass>
                                    <CalcCG>6.35</CalcCG>
                                    <DensityType>0</DensityType>
                                    <RadialLoc>0.0</RadialLoc>
                                    <RadialAngle>0.0</RadialAngle>
                                    <LocationMode>0</LocationMode>
                                    <Len>12.7</Len>
                                    <FinishCode>0</FinishCode>
                                    <SerialNo>6</SerialNo>
                                    <OD>25.044</OD>
                                    <ID>24.79</ID>
                                    <UsageCode>0</UsageCode>
                                    <AutoSize>0</AutoSize>
                                </Ring>
                            </AttachedParts>
                        </BodyTube>
                        <LaunchLug>
                            <KnownMass>0.4735920088786065</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>paper</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>114.3</Xb>
                            <CalcMass>0.4735920088786065</CalcMass>
                            <CalcCG>12.7</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>6.293</OD>
                            <ID>4.293</ID>
                        </LaunchLug>
                        <FinSet>
                            <KnownMass>11.024814291230546</KnownMass>
                            <Density>128.147704</Density>
                            <Material>Balsa</Material>
                            <Name>Fin set</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>127.0</Xb>
                            <CalcMass>11.024814291230546</CalcMass>
                            <CalcCG>103.73526299258252</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>1</FinishCode>
                            <SerialNo>8</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>127.0</RootChord>
                            <TipChord>50.8</TipChord>
                            <SemiSpan>76.2</SemiSpan>
                            <SweepDistance>131.982280316026</SweepDistance>
                            <Thickness>3.175</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <MassObject>
                            <KnownMass>3.685</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Inside Fins</Name>
                            <KnownCG>196.85</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>196.85</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>1.0414</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass object</Name>
                            <KnownCG>111.125</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>111.125</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>5.08</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>9.154341328774686</KnownMass>
                            <Density>0.0023106632877499997</Density>
                            <Material>Polyethylene LDPE</Material>
                            <Name>Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>63.5</Xb>
                            <CalcMass>9.154341328774686</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <Dia>609.6</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>609.6</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>6.59E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>1/32 In. kevlar</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <Ring>
                            <KnownMass>1.3222115639729557</KnownMass>
                            <Density>688.793909</Density>
                            <Material>Cardboard</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>241.3</Xb>
                            <CalcMass>1.3222115639729557</CalcMass>
                            <CalcCG>0.254</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.508</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>73.66</OD>
                            <ID>24.79</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.983317345959434</KnownMass>
                            <Density>688.793909</Density>
                            <Material>Cardboard</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>146.05</Xb>
                            <CalcMass>1.983317345959434</CalcMass>
                            <CalcCG>0.381</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.762</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <OD>73.66</OD>
                            <ID>24.79</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>