#!/bin/bash
# RocketChip clang-tidy audit runner
#
# Runs clang-tidy across all production source files and writes
# per-file output to a timestamped directory.
#
# Tiers:
#   1. clang-tidy (127 checks, existing)
#   2. lizard cyclomatic complexity (JSF AV Rule 3, CCN <= 20)
#   3. RP2350 platform guards (Flight-Critical files only)
#   4. Prior Art checks (drivers only)
#
# Prerequisites:
#   - LLVM/clang-tidy installed (C:/Program Files/LLVM/bin/)
#   - Target build completed: cmake -B build -G Ninja && ninja -C build
#     (generates compile_commands.json)
#   - lizard installed: pip install lizard
#
# Usage:
#   bash scripts/run_clang_tidy.sh           # Full audit
#   bash scripts/run_clang_tidy.sh src/main.cpp  # Single file

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CLANG_TIDY="C:/Program Files/LLVM/bin/clang-tidy.exe"
BUILD_DIR="${REPO_ROOT}/build"
TOOLCHAIN="C:/Users/pow-w/.pico-sdk/toolchain/14_2_Rel1"

# Verify prerequisites
if [[ ! -x "${CLANG_TIDY}" ]]; then
    echo "ERROR: clang-tidy not found at ${CLANG_TIDY}"
    exit 1
fi
if [[ ! -f "${BUILD_DIR}/compile_commands.json" ]]; then
    echo "ERROR: compile_commands.json not found. Run: cmake -B build -G Ninja && ninja -C build"
    exit 1
fi

# Extra args for ARM cross-compilation context
EXTRA_ARGS=(
    --extra-arg="--sysroot=${TOOLCHAIN}/arm-none-eabi"
    --extra-arg="--target=armv8m.main-none-eabi"
    --extra-arg="-isystem"
    --extra-arg="${TOOLCHAIN}/arm-none-eabi/include/c++/14.2.1"
    --extra-arg="-isystem"
    --extra-arg="${TOOLCHAIN}/arm-none-eabi/include/c++/14.2.1/arm-none-eabi/thumb/v8-m.main+fp/softfp"
    --extra-arg="-Wno-format-security"
    --extra-arg="-Wno-gnu-zero-variadic-macro-arguments"
)

# PRODUCTION_FILES synced from CMakeLists.txt (portable, fixes stale list + includes all Stage 8 files)
# Excludes auto-generated and benchmark/tool files (not production code):
#   eskf_codegen.cpp  — auto-generated by scripts/generate_fpft.py (deviation CG-1)
#   ud_benchmark.cpp  — benchmark tool, relaxed standards
#   mat_benchmark.cpp — benchmark tool, relaxed standards
PRODUCTION_FILES=($(grep -o 'src/[^[:space:]]*\.cpp' "${REPO_ROOT}/CMakeLists.txt" | \
    grep -v 'eskf_codegen\.cpp' | grep -v 'ud_benchmark\.cpp' | grep -v 'mat_benchmark\.cpp' | \
    sort -u))
if [ ${#PRODUCTION_FILES[@]} -eq 0 ]; then
    echo "ERROR: Could not parse PRODUCTION_FILES from CMakeLists.txt"
    exit 1
fi

# If specific files passed as args, use those instead
if [[ $# -gt 0 ]]; then
    PRODUCTION_FILES=("$@")
fi

# Output directory
TIMESTAMP=$(date +%Y-%m-%d)
OUT_DIR="${REPO_ROOT}/logs/clang-tidy-${TIMESTAMP}"
mkdir -p "${OUT_DIR}"

echo "=== RocketChip clang-tidy Audit ==="
echo "Tool: $("${CLANG_TIDY}" --version 2>&1 | grep 'LLVM version')"
echo "Files: ${#PRODUCTION_FILES[@]}"
echo "Output: ${OUT_DIR}/"
echo ""

TOTAL_WARNINGS=0
SUMMARY_FILE="${OUT_DIR}/summary.txt"
> "${SUMMARY_FILE}"

for src in "${PRODUCTION_FILES[@]}"; do
    FILE_PATH="${REPO_ROOT}/${src}"
    if [[ ! -f "${FILE_PATH}" ]]; then
        echo "SKIP: ${src} (not found)"
        continue
    fi

    BASENAME=$(basename "${src}" .cpp)
    OUT_FILE="${OUT_DIR}/${BASENAME}.txt"

    echo -n "  ${src} ... "

    # Run clang-tidy, capture output
    "${CLANG_TIDY}" "${FILE_PATH}" -p "${BUILD_DIR}/" "${EXTRA_ARGS[@]}" \
        2>&1 | grep -v "^[0-9]* warnings generated" | grep -v "^Suppressed" | grep -v "^Use -header-filter" \
        > "${OUT_FILE}" || true

    # Count warnings (lines matching "warning:" in our code)
    COUNT=$(grep -c "warning:" "${OUT_FILE}" 2>/dev/null || true)
    COUNT=${COUNT:-0}
    # Ensure COUNT is a single integer
    COUNT=$(echo "${COUNT}" | tail -1 | grep -o '[0-9]*' | head -1)
    COUNT=${COUNT:-0}
    TOTAL_WARNINGS=$((TOTAL_WARNINGS + COUNT))

    echo "${COUNT} warnings"
    printf "%-50s %d\n" "${src}" "${COUNT}" >> "${SUMMARY_FILE}"
done

# === TIER 2: JSF AV + JPL + Power of 10 (lizard cyclomatic complexity) ===
echo ""
echo "=== Tier 2: JSF AV + JPL (lizard cyclomatic complexity) ==="
LIZARD_CMD=""
if command -v lizard &> /dev/null; then
    LIZARD_CMD="lizard"
elif python -m lizard --version &> /dev/null 2>&1; then
    LIZARD_CMD="python -m lizard"
else
    echo "ERROR: lizard not found. Run once: pip install lizard"
    exit 1
fi
# Run lizard — exit code 1 means warnings found (not a script error)
${LIZARD_CMD} -l cpp -C 20 -L 60 -a 5 --warnings_only "${PRODUCTION_FILES[@]}" \
    | tee "${OUT_DIR}/tier2-lizard.txt" || true
if [ -s "${OUT_DIR}/tier2-lizard.txt" ]; then
    echo "WARNING: Tier 2 Lizard violations found (see tier2-lizard.txt)"
else
    echo "Lizard metrics passed"
fi

# === TIER 3: RP2350 Bare-Metal Platform Constraints (Flight-Critical only) ===
echo ""
echo "=== Tier 3: RP2350 Platform Guards (Flight-Critical files only) ==="
FLIGHT_CRITICAL_FILES=($(printf '%s\n' "${PRODUCTION_FILES[@]}" | grep -E 'src/(drivers/(icm20948|baro_dps310|i2c_bus|spi_bus|gps_|rfm95w)|flight_director)' || true))
if [ ${#FLIGHT_CRITICAL_FILES[@]} -gt 0 ]; then
    if grep -n -E 'printf|cout|scanf' "${FLIGHT_CRITICAL_FILES[@]}" 2>/dev/null | \
       grep -vE 'DBG_PRINT|DBG_ERROR|#ifdef DEBUG|//|/\*|stdio_usb_connected|snprintf' \
       > "${OUT_DIR}/tier3-stdio.txt" 2>/dev/null; then
        echo "WARNING: Unguarded stdio in Flight-Critical paths (see tier3-stdio.txt)"
        cat "${OUT_DIR}/tier3-stdio.txt"
    else
        echo "RP2350 guards ok"
    fi
else
    echo "RP2350 guards ok (no flight-critical files found)"
fi

# === TIER 4: Documentation & Process Checks (drivers only) ===
echo ""
echo "=== Tier 4: Prior Art (drivers only) ==="
DRIVER_FILES=($(printf '%s\n' "${PRODUCTION_FILES[@]}" | grep -E 'src/drivers/' || true))
if [ ${#DRIVER_FILES[@]} -gt 0 ]; then
    MISSING_PA=$(grep -L 'Prior Art:' "${DRIVER_FILES[@]}" 2>/dev/null || true)
    if [ -n "${MISSING_PA}" ]; then
        echo "WARNING: Driver files missing Prior Art comment block:"
        echo "${MISSING_PA}" | sed 's/^/    /'
    else
        echo "Prior Art ok"
    fi
else
    echo "Prior Art ok (no driver files found)"
fi

echo ""
echo "Total: ${TOTAL_WARNINGS} clang-tidy warnings across ${#PRODUCTION_FILES[@]} files"
echo "Summary: ${SUMMARY_FILE}"
printf "\nTotal: %d warnings\n" "${TOTAL_WARNINGS}" >> "${SUMMARY_FILE}"
