# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (c) 2025-2026 Rocket Chip Project
# =============================================================================
# Configuration Wizard — .cfg File Emitter
#
# Takes a parameter dict (from derivation.py) and produces a formatted .cfg
# file string matching the existing profile format. Adds a wizard header
# with vehicle type, timestamp, CRC32 hash, and any acknowledged gates.
# =============================================================================

from __future__ import annotations
import zlib
from datetime import datetime, timezone
from typing import Optional


# =============================================================================
# Section layout — matches existing .cfg file structure
#
# Each section: (header_comment, list of (cfg_key, inline_comment))
# Keys not in any section are appended at the end under "OTHER".
# =============================================================================

SECTIONS = [
    ("TIMEOUTS", [
        ("ARMED_TIMEOUT_MS", "Auto-disarm if no launch"),
        ("ABORT_TIMEOUT_MS", "ABORT state timeout"),
        ("COAST_TIMEOUT_MS", "Missed apogee fallback"),
    ]),
    ("LAUNCH DETECTION", [
        ("LAUNCH_ACCEL", "m/s^2"),
        ("LAUNCH_HOLD_MS", "ms"),
    ]),
    ("BURNOUT DETECTION", [
        ("BURNOUT_ACCEL", "m/s^2"),
        ("BURNOUT_HOLD_MS", "ms"),
        ("BURNOUT_BACKUP_MS", "Max time in BOOST before forced coast"),
    ]),
    ("APOGEE DETECTION", [
        ("APOGEE_VEL", "m/s"),
        ("APOGEE_HOLD_MS", "ms"),
        ("BARO_HOLD_MS", "Baro derivative backup"),
        ("APOGEE_BOTH", "1=AND (vel+baro), 0=OR"),
    ]),
    ("MAIN PARACHUTE DEPLOYMENT", [
        ("MAIN_ALT_M", "meters AGL"),
        ("MAIN_HOLD_MS", "ms"),
        ("MAIN_BACKUP_MS", "Max time in drogue before forced main"),
    ]),
    ("LANDING DETECTION", [
        ("LAND_VEL", "m/s"),
        ("LAND_HOLD_MS", "ms"),
    ]),
    ("SAFETY LOCKOUTS", [
        ("DEPLOY_LOCKOUT_MPS", "m/s — max speed for chute deploy"),
        ("APOGEE_LOCKOUT_MS", "Min time after launch before apogee"),
        ("EMERG_DEPLOY", "1=skip lockouts (HAB), 0=respect (rockets)"),
    ]),
    ("PYROTECHNIC CHANNELS", [
        ("HAS_PYRO", "1=pyro channels available, 0=no pyro"),
        ("ABORT_DROGUE_BOOST", "Fire drogue on ABORT from BOOST"),
        ("ABORT_DROGUE_COAST", "Fire drogue on ABORT from COAST"),
    ]),
    ("PRE-ARM REQUIREMENTS", [
        ("REQUIRE_GPS", "1=required, 0=optional"),
        ("REQUIRE_MAG", "1=required, 0=optional"),
        ("REQUIRE_RADIO", "1=required, 0=optional"),
    ]),
    ("PIO BACKUP DEPLOYMENT TIMERS", [
        ("DROGUE_TIMER_S", "seconds from ARM"),
        ("MAIN_TIMER_S", "seconds from ARM"),
    ]),
    ("DEFAULT LOCATION", [
        ("DEFAULT_LAT", "degrees North"),
        ("DEFAULT_LON", "degrees East (negative = West)"),
    ]),
    ("SAFE MODE BEHAVIOR", [
        ("SAFE_MODE_ACTION", "0=safe mode, 1=safe+radio recovery"),
    ]),
    ("RADIO CONFIGURATION", [
        ("RADIO_MODE", "0=TX, 1=RX, 2=relay"),
        ("RADIO_PROTOCOL", "0=CCSDS, 1=MAVLink"),
        ("RADIO_RATE_HZ", "Hz"),
        ("RADIO_POWER_DBM", "dBm (2-20)"),
    ]),
]

# Q/R phase fields — always 8 values per row
QR_SECTION_KEYS = [
    "Q_ATT_SCALE", "Q_VEL_SCALE", "Q_ABIAS_SCALE", "Q_GBIAS_SCALE",
    "R_BARO", "R_MAG", "R_GPS_POS", "R_GPS_VEL",
]

QR_EXTRA_KEYS = ["QR_RAMP_STEPS"]


# =============================================================================
# Emit .cfg text
# =============================================================================

def emit(params: dict[str, str],
         vehicle_desc: str = "",
         acknowledged_gates: Optional[list[str]] = None) -> str:
    """Generate formatted .cfg file text from a parameter dict.

    Args:
        params: Complete parameter dict from derivation.
        vehicle_desc: Human description (e.g., "Rocket / Single Stage / Dual Deploy")
        acknowledged_gates: List of gate messages the user acknowledged.

    Returns:
        Formatted .cfg file content as a string.
    """
    lines: list[str] = []

    # --- Wizard header ---
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines.append("# =============================================================================")
    lines.append(f"# RocketChip Mission Profile — Generated by Configuration Wizard")
    lines.append(f"#")
    lines.append(f"# Vehicle:   {vehicle_desc}" if vehicle_desc else "# Vehicle:   (not specified)")
    lines.append(f"# Generated: {now}")

    if acknowledged_gates:
        lines.append(f"#")
        lines.append(f"# Acknowledged advisories:")
        for gate_msg in acknowledged_gates:
            lines.append(f"#   - {gate_msg}")

    lines.append("# =============================================================================")
    lines.append("")

    # --- Profile name ---
    profile_name = params.get("PROFILE_NAME", "Custom")
    lines.append(f"PROFILE_NAME        {profile_name}")
    lines.append("")

    # --- Sectioned parameters ---
    emitted_keys: set[str] = {"PROFILE_NAME"}

    for section_name, fields in SECTIONS:
        # Only emit section if at least one key exists
        section_keys = [k for k, _ in fields if k in params]
        if not section_keys:
            continue

        lines.append(f"# =============================================================================")
        lines.append(f"# {section_name}")
        lines.append(f"# =============================================================================")
        lines.append("")

        for cfg_key, comment in fields:
            if cfg_key in params:
                value = params[cfg_key]
                # Pad key to 20 chars for alignment
                padded = f"{cfg_key:<20s}"
                lines.append(f"{padded}{value:<16s}# {comment}")
                emitted_keys.add(cfg_key)

        lines.append("")

    # --- Phase Q/R section ---
    qr_present = any(k in params for k in QR_SECTION_KEYS)
    if qr_present:
        lines.append("# =============================================================================")
        lines.append("# PHASE Q/R — ESKF Adaptive Estimation")
        lines.append("# =============================================================================")
        lines.append("# Column order: IDLE ARMED BOOST COAST DROGUE_DESC MAIN_DESC LANDED ABORT")
        lines.append("")

        for cfg_key in QR_SECTION_KEYS:
            if cfg_key in params:
                value = params[cfg_key]
                padded = f"{cfg_key:<16s}"
                lines.append(f"{padded}{value}")
                emitted_keys.add(cfg_key)

        lines.append("")

        for cfg_key in QR_EXTRA_KEYS:
            if cfg_key in params:
                value = params[cfg_key]
                padded = f"{cfg_key:<20s}"
                lines.append(f"{padded}{value}")
                emitted_keys.add(cfg_key)

        lines.append("")

    # --- Any remaining keys not in sections ---
    remaining = {k: v for k, v in params.items() if k not in emitted_keys}
    if remaining:
        lines.append("# =============================================================================")
        lines.append("# OTHER")
        lines.append("# =============================================================================")
        lines.append("")
        for cfg_key, value in sorted(remaining.items()):
            padded = f"{cfg_key:<20s}"
            lines.append(f"{padded}{value}")
        lines.append("")

    content = '\n'.join(lines) + '\n'

    # --- Append CRC32 hash as a comment at the end ---
    cfg_hash = zlib.crc32(content.encode('utf-8')) & 0xFFFFFFFF
    content += f"# Config hash: 0x{cfg_hash:08X}\n"

    return content


def compute_hash(cfg_content: str) -> int:
    """Compute CRC32 hash of .cfg content (before hash line is appended).

    This matches what generate_profile.py should embed as kProfileConfigHash.
    """
    # Strip any existing hash line before computing
    lines = cfg_content.split('\n')
    clean_lines = [l for l in lines if not l.startswith('# Config hash:')]
    clean = '\n'.join(clean_lines)
    return zlib.crc32(clean.encode('utf-8')) & 0xFFFFFFFF
