# capture_condensation_evidence.ps1
# The single source of truth for generating clean evidence files in {SCRATCH}.
# Run after any change to DESIGN.md or related.
# Produces only the required files for the verification plan.
# Uses UTF8 no-BOM. Exits 1 on any mojibake detection.
# Also validates the DATA_PRESERVATION_MANIFEST.

$ErrorActionPreference = 'Stop'

$utf8NoBom = New-Object System.Text.UTF8Encoding $false

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)  # starcom/docs/scripts -> repo root approx; adjust if needed
Set-Location $repoRoot

$scratch = 'C:\Users\pow-w\AppData\Local\Temp\grok-goal-0c77f1f8fcc0\implementer'
New-Item -ItemType Directory -Force -Path $scratch | Out-Null

function Write-Clean {
  param([string]$path, [string]$content)
  [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
  $readBack = [System.IO.File]::ReadAllText($path)
  # Detect common mojibake / bad chars from previous captures
  if ($readBack -match '[\u00A0�]|A�|â€|Starcom �|\?{2,}' -or $readBack -match '60A�') {
    Write-Error "Mojibake or bad encoding detected in $path"
    exit 1
  }
  Write-Host "Wrote clean: $path"
}

# 1. git_tree_evidence.txt (verif #1)
$branch = git branch --show-current
$statusStarcom = git status --porcelain -- 'starcom/' | Out-String
$logStarcom = git log --oneline -5 --all -- 'starcom/docs/' 'starcom/*.md' | Out-String
$diffNames = git diff --name-only main...HEAD -- 'starcom/' | Out-String
$gitEvidence = @"
=== GIT_TREE_EVIDENCE (generated by capture script) ===
Branch: $branch
git status --porcelain -- 'starcom/':
$statusStarcom
git log --oneline -5 for starcom paths:
$logStarcom
git diff --name-only main...HEAD -- 'starcom/':
$diffNames
Note: Only starcom/ paths are in scope for condensation. Other untracked/dirty (agent-tools/, mcps/, L2P5*) are pre-existing and excluded via filters. No historical documents deleted.
"@
Write-Clean "$scratch/git_tree_evidence.txt" $gitEvidence

# 2. all_docs_list.txt (verif #2)
$list = Get-ChildItem -Recurse starcom -Include *.md | Sort-Object FullName | Select-Object -ExpandProperty FullName | Out-String
$lsOut = (Get-ChildItem starcom, starcom/docs, starcom/docs/research | Out-String)
$allList = "=== ALL STARCOM *.md (sorted) ===`n$list`n=== ls tree ===`n$lsOut"
Write-Clean "$scratch/all_docs_list.txt" $allList

# 3. all_docs_content.txt (verif #2 - head-200 or full for short)
$coreFiles = @(
  'starcom/docs/README.md',
  'starcom/docs/WORKING_HERE.md',
  'starcom/docs/DESIGN.md',
  'starcom/docs/comparison.md',
  'starcom/docs/design_record_claude.md',
  'starcom/docs/research/ccsds_domain_claude.md',
  'starcom/docs/research/ccsds_domain_grok.md',
  'starcom/docs/research/library_craft_claude.md',
  'starcom/docs/research/library_craft_grok.md',
  'starcom/README.md',
  'starcom/STATUS.md',
  'starcom/CHANGELOG.md',
  'starcom/src/ccsds/README.md'
)
$contentAll = "=== ALL_DOCS_CONTENT (generated by capture script, proper encoding) ===`n"
foreach ($f in $coreFiles) {
  if (Test-Path $f) {
    $lines = Get-Content $f -TotalCount 200
    $head = $lines | Out-String
    $contentAll += "----- BEGIN $f (head-200 or full) -----`n$head----- END $f -----`n"
  } else {
    $contentAll += "MISSING: $f`n"
  }
}
Write-Clean "$scratch/all_docs_content.txt" $contentAll

# 4. design_condensed.txt = full current DESIGN.md
$designText = [System.IO.File]::ReadAllText('starcom/docs/DESIGN.md')
Write-Clean "$scratch/design_condensed.txt" $designText

# 5. conflict_table.txt (verif #3) - extract key parts from DESIGN
$tableGrep = Select-String -Path 'starcom/docs/DESIGN.md' -Pattern 'Agreement / Conflict|PHY waveform|sans-I/O core|USLP vs V-3|PLCW vs CLCW|FOP-1 \(COP-1 sender\)|FARM-1|RP2350 PIO' -Context 1 | Out-String
$conflictTable = "=== CONFLICT TABLE / KEY ROWS (from DESIGN) ===`n$tableGrep`n(Full table lives in DESIGN.md #1)"
Write-Clean "$scratch/conflict_table.txt" $conflictTable

# 6. final_evidence.log (verif #5)
$final = @"
=== FINAL_EVIDENCE (generated $(Get-Date -Format o)) ===
Branch: $branch
starcom-only changed (from diff): 
$diffNames
Main has zero uncommitted starcom condensation changes (see git_tree).
No merge performed. All evidence produced by this script only.
"@
Write-Clean "$scratch/final_evidence.log" $final

# 7. Manifest validation (no-loss)
$manifestPath = 'starcom/docs/DATA_PRESERVATION_MANIFEST.md'
$manifest = Get-Content $manifestPath -Raw
$tokens = @(
  '§0 canonical scope',
  'FOP-1 (COP-1 sender)',
  '6 states x 46 events',
  'PLCW is a 16-bit fixed-length SPDU',
  'architecturally complete \+ feature-incremental',
  'generator test idea',
  'D-1',
  'D-5',
  'LunaNet',
  '<50 km',
  'Part 97',
  'feature-ownership map',
  'three first-class',
  'no-heap-after-init'
)

foreach ($tok in $tokens) {
  $found = $false
  if (Select-String -Path 'starcom/docs/DESIGN.md' -Pattern $tok -Quiet) { $found = $true }
  # Also check some REFs for completeness
  if (-not $found -and (Select-String -Path 'starcom/docs/design_record_claude.md' -Pattern $tok -Quiet)) { $found = $true }
  if (-not $found -and (Select-String -Path 'starcom/docs/comparison.md' -Pattern $tok -Quiet)) { $found = $true }
  if (-not $found) {
    Write-Error "Manifest token not found in DESIGN or primary REF: $tok"
    exit 1
  }
}
Write-Host "Manifest validation passed."

Write-Host "=== CAPTURE COMPLETE - all SCRATCH files clean, no mojibake, scope isolated to starcom/ ==="
Write-Host "Run this script again after any DESIGN change."
exit 0
